/**
 * Tools configuration file
 * Contains all 67 PDF tools with their properties, categories, and related tools
 * Migrated from BentoPDF and enhanced for PDFCraft
 */

import { Tool, ToolCategory } from '@/types/tool';

/**
 * Default file size limits - No restrictions
 */
const DEFAULT_MAX_FILE_SIZE = Infinity; // No limit
const LARGE_FILE_SIZE = Infinity; // No limit

/**
 * All tools configuration
 * Each tool must have:
 * - Unique id and slug
 * - Exactly one category from the 6 defined categories
 * - At least 2 related tools
 */
export const tools: Tool[] = [
  // ==================== ORGANIZE & MANAGE ====================
  {
    id: 'pdf-multi-tool',
    slug: 'pdf-multi-tool',
    icon: 'pencil-ruler',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: LARGE_FILE_SIZE,
    maxFiles: 10,
    features: ['merge', 'split', 'organize', 'delete', 'rotate', 'add-blank', 'extract', 'duplicate'],
    relatedTools: ['merge-pdf', 'split-pdf', 'organize-pdf'],
  },
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    icon: 'combine',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: LARGE_FILE_SIZE,
    maxFiles: 100,
    features: ['combine-multiple', 'preserve-bookmarks', 'reorder'],
    relatedTools: ['split-pdf', 'organize-pdf', 'alternate-merge'],
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    icon: 'scissors',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['page-range', 'multiple-outputs', 'extract-pages'],
    relatedTools: ['merge-pdf', 'extract-pages', 'delete-pages'],
  },

  {
    id: 'compress-pdf',
    slug: 'compress-pdf',
    icon: 'zap',
    category: 'optimize-repair',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: LARGE_FILE_SIZE,
    maxFiles: 10,
    features: ['reduce-size', 'optimize-images', 'remove-metadata'],
    relatedTools: ['linearize-pdf', 'repair-pdf', 'sanitize-pdf'],
  },
  {
    id: 'edit-pdf',
    slug: 'edit-pdf',
    icon: 'pocket-knife',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['annotate', 'highlight', 'redact', 'comment', 'shapes', 'images', 'search'],
    relatedTools: ['sign-pdf', 'add-watermark', 'form-filler'],
  },
  {
    id: 'jpg-to-pdf',
    slug: 'jpg-to-pdf',
    icon: 'image-up',
    category: 'convert-to-pdf',
    acceptedFormats: ['.jpg', '.jpeg'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 100,
    features: ['multiple-images', 'page-order', 'page-size'],
    relatedTools: ['png-to-pdf', 'image-to-pdf', 'pdf-to-jpg'],
  },
  {
    id: 'sign-pdf',
    slug: 'sign-pdf',
    icon: 'pen-tool',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['draw-signature', 'type-signature', 'upload-signature', 'multiple-signatures'],
    relatedTools: ['edit-pdf', 'form-filler', 'add-stamps'],
  },
  {
    id: 'crop-pdf',
    slug: 'crop-pdf',
    icon: 'crop',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['trim-margins', 'custom-crop', 'all-pages'],
    relatedTools: ['edit-pdf', 'fix-page-size', 'page-dimensions'],
  },
  {
    id: 'extract-pages',
    slug: 'extract-pages',
    icon: 'ungroup',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['select-pages', 'multiple-outputs', 'page-range'],
    relatedTools: ['split-pdf', 'delete-pages', 'organize-pdf'],
  },
  {
    id: 'organize-pdf',
    slug: 'organize-pdf',
    icon: 'files',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['reorder-pages', 'duplicate-pages', 'delete-pages', 'drag-drop'],
    relatedTools: ['merge-pdf', 'extract-pages', 'delete-pages'],
  },
  {
    id: 'delete-pages',
    slug: 'delete-pages',
    icon: 'trash-2',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['select-pages', 'preview', 'batch-delete'],
    relatedTools: ['extract-pages', 'organize-pdf', 'split-pdf'],
  },

  // ==================== EDIT & ANNOTATE ====================
  {
    id: 'bookmark',
    slug: 'bookmark',
    icon: 'bookmark',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['add-bookmarks', 'edit-bookmarks', 'import-bookmarks', 'delete-bookmarks', 'extract-bookmarks'],
    relatedTools: ['table-of-contents', 'edit-pdf', 'edit-metadata'],
  },
  {
    id: 'table-of-contents',
    slug: 'table-of-contents',
    icon: 'list',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['generate-toc', 'from-bookmarks', 'custom-style'],
    relatedTools: ['bookmark', 'page-numbers', 'header-footer'],
  },
  {
    id: 'page-numbers',
    slug: 'page-numbers',
    icon: 'list-ordered',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['custom-position', 'custom-format', 'start-number', 'skip-pages'],
    relatedTools: ['header-footer', 'add-watermark', 'table-of-contents'],
  },

  {
    id: 'add-watermark',
    slug: 'add-watermark',
    icon: 'droplets',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['text-watermark', 'image-watermark', 'position', 'opacity', 'rotation'],
    relatedTools: ['header-footer', 'page-numbers', 'add-stamps'],
  },
  {
    id: 'header-footer',
    slug: 'header-footer',
    icon: 'pilcrow',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['custom-text', 'page-numbers', 'date', 'position'],
    relatedTools: ['page-numbers', 'add-watermark', 'table-of-contents'],
  },
  {
    id: 'invert-colors',
    slug: 'invert-colors',
    icon: 'contrast',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['dark-mode', 'invert-all', 'preserve-images'],
    relatedTools: ['background-color', 'text-color', 'pdf-to-greyscale'],
  },
  {
    id: 'background-color',
    slug: 'background-color',
    icon: 'palette',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['custom-color', 'all-pages', 'selected-pages'],
    relatedTools: ['invert-colors', 'text-color', 'add-watermark'],
  },
  {
    id: 'text-color',
    slug: 'text-color',
    icon: 'type',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['change-text-color', 'all-text', 'selected-text'],
    relatedTools: ['background-color', 'invert-colors', 'edit-pdf'],
  },
  {
    id: 'add-stamps',
    slug: 'add-stamps',
    icon: 'stamp',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['image-stamps', 'preset-stamps', 'custom-position'],
    relatedTools: ['sign-pdf', 'add-watermark', 'edit-pdf'],
  },
  {
    id: 'remove-annotations',
    slug: 'remove-annotations',
    icon: 'eraser',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['remove-comments', 'remove-highlights', 'remove-links', 'selective-removal'],
    relatedTools: ['edit-pdf', 'flatten-pdf', 'sanitize-pdf'],
  },
  {
    id: 'form-filler',
    slug: 'form-filler',
    icon: 'square-pen',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['fill-forms', 'xfa-support', 'save-data', 'flatten-after'],
    relatedTools: ['form-creator', 'sign-pdf', 'edit-pdf'],
  },
  {
    id: 'form-creator',
    slug: 'form-creator',
    icon: 'file-input',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['text-fields', 'checkboxes', 'dropdowns', 'drag-drop'],
    relatedTools: ['form-filler', 'edit-pdf', 'sign-pdf'],
  },
  {
    id: 'remove-blank-pages',
    slug: 'remove-blank-pages',
    icon: 'file-minus-2',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['auto-detect', 'threshold-setting', 'preview'],
    relatedTools: ['delete-pages', 'organize-pdf', 'compress-pdf'],
  },

  // ==================== CONVERT TO PDF ====================
  {
    id: 'image-to-pdf',
    slug: 'image-to-pdf',
    icon: 'images',
    category: 'convert-to-pdf',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp', '.bmp', '.tiff', '.tif', '.svg', '.heic'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 100,
    features: ['multiple-formats', 'page-order', 'page-size', 'orientation'],
    relatedTools: ['jpg-to-pdf', 'png-to-pdf', 'pdf-to-jpg'],
  },
  {
    id: 'png-to-pdf',
    slug: 'png-to-pdf',
    icon: 'image-up',
    category: 'convert-to-pdf',
    acceptedFormats: ['.png'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 100,
    features: ['multiple-images', 'transparency', 'page-size'],
    relatedTools: ['jpg-to-pdf', 'image-to-pdf', 'pdf-to-png'],
  },

  {
    id: 'webp-to-pdf',
    slug: 'webp-to-pdf',
    icon: 'image-up',
    category: 'convert-to-pdf',
    acceptedFormats: ['.webp'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 100,
    features: ['multiple-images', 'page-size', 'quality'],
    relatedTools: ['jpg-to-pdf', 'png-to-pdf', 'pdf-to-webp'],
  },
  {
    id: 'svg-to-pdf',
    slug: 'svg-to-pdf',
    icon: 'pen-tool',
    category: 'convert-to-pdf',
    acceptedFormats: ['.svg'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 100,
    features: ['vector-quality', 'multiple-files', 'page-size'],
    relatedTools: ['image-to-pdf', 'png-to-pdf', 'jpg-to-pdf'],
  },
  {
    id: 'bmp-to-pdf',
    slug: 'bmp-to-pdf',
    icon: 'image',
    category: 'convert-to-pdf',
    acceptedFormats: ['.bmp'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 100,
    features: ['multiple-images', 'page-size', 'compression'],
    relatedTools: ['jpg-to-pdf', 'png-to-pdf', 'pdf-to-bmp'],
  },
  {
    id: 'heic-to-pdf',
    slug: 'heic-to-pdf',
    icon: 'smartphone',
    category: 'convert-to-pdf',
    acceptedFormats: ['.heic', '.heif'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 100,
    features: ['iphone-photos', 'multiple-images', 'page-size'],
    relatedTools: ['jpg-to-pdf', 'image-to-pdf', 'png-to-pdf'],
  },
  {
    id: 'tiff-to-pdf',
    slug: 'tiff-to-pdf',
    icon: 'layers',
    category: 'convert-to-pdf',
    acceptedFormats: ['.tiff', '.tif'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 100,
    features: ['multi-page-tiff', 'high-quality', 'page-size'],
    relatedTools: ['image-to-pdf', 'pdf-to-tiff', 'jpg-to-pdf'],
  },
  {
    id: 'txt-to-pdf',
    slug: 'txt-to-pdf',
    icon: 'file-pen',
    category: 'convert-to-pdf',
    acceptedFormats: ['.txt'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['font-selection', 'page-size', 'margins'],
    relatedTools: ['json-to-pdf', 'image-to-pdf', 'merge-pdf'],
  },
  {
    id: 'json-to-pdf',
    slug: 'json-to-pdf',
    icon: 'file-code',
    category: 'convert-to-pdf',
    acceptedFormats: ['.json'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['formatted-output', 'syntax-highlighting', 'page-size'],
    relatedTools: ['pdf-to-json', 'txt-to-pdf', 'merge-pdf'],
  },
  {
    id: 'psd-to-pdf',
    slug: 'psd-to-pdf',
    icon: 'image',
    category: 'convert-to-pdf',
    acceptedFormats: ['.psd', '.psb'],
    outputFormat: 'pdf',
    maxFileSize: LARGE_FILE_SIZE,
    maxFiles: 100,
    features: ['multiple-files', 'psd-layers', 'page-size'],
    relatedTools: ['image-to-pdf', 'jpg-to-pdf', 'png-to-pdf'],
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    icon: 'file-text',
    category: 'convert-to-pdf',
    acceptedFormats: ['.docx', '.doc'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['preserve-layout', 'preserve-formatting', 'extract-text'],
    relatedTools: ['pdf-to-docx', 'txt-to-pdf', 'excel-to-pdf'],
  },
  {
    id: 'excel-to-pdf',
    slug: 'excel-to-pdf',
    icon: 'file-spreadsheet',
    category: 'convert-to-pdf',
    acceptedFormats: ['.xlsx', '.xls'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['preserve-tables', 'multiple-sheets', 'page-layout'],
    relatedTools: ['pdf-to-excel', 'word-to-pdf', 'pptx-to-pdf'],
  },
  {
    id: 'pptx-to-pdf',
    slug: 'pptx-to-pdf',
    icon: 'presentation',
    category: 'convert-to-pdf',
    acceptedFormats: ['.pptx', '.ppt'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['preserve-slides', 'preserve-layout', 'high-quality'],
    relatedTools: ['pdf-to-pptx', 'word-to-pdf', 'excel-to-pdf'],
  },
  {
    id: 'xps-to-pdf',
    slug: 'xps-to-pdf',
    icon: 'file-box',
    category: 'convert-to-pdf',
    acceptedFormats: ['.xps'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['preserve-layout', 'high-fidelity', 'vector-graphics'],
    relatedTools: ['word-to-pdf', 'image-to-pdf', 'merge-pdf'],
  },
  {
    id: 'rtf-to-pdf',
    slug: 'rtf-to-pdf',
    icon: 'file-type',
    category: 'convert-to-pdf',
    acceptedFormats: ['.rtf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['preserve-formatting', 'extract-text', 'page-size'],
    relatedTools: ['word-to-pdf', 'txt-to-pdf', 'merge-pdf'],
  },
  {
    id: 'epub-to-pdf',
    slug: 'epub-to-pdf',
    icon: 'book-open',
    category: 'convert-to-pdf',
    acceptedFormats: ['.epub'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['preserve-formatting', 'preserve-images', 'chapter-structure'],
    relatedTools: ['word-to-pdf', 'txt-to-pdf', 'html-to-pdf'],
  },
  {
    id: 'mobi-to-pdf',
    slug: 'mobi-to-pdf',
    icon: 'book-marked',
    category: 'convert-to-pdf',
    acceptedFormats: ['.mobi', '.azw', '.azw3'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['preserve-formatting', 'preserve-images', 'chapter-structure'],
    relatedTools: ['epub-to-pdf', 'fb2-to-pdf', 'txt-to-pdf'],
  },
  {
    id: 'djvu-to-pdf',
    slug: 'djvu-to-pdf',
    icon: 'file-scan',
    category: 'convert-to-pdf',
    acceptedFormats: ['.djvu', '.djv'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['preserve-formatting', 'dpi-setting', 'quality-setting'],
    relatedTools: ['image-to-pdf', 'scan-to-pdf', 'ocr-pdf'],
  },
  {
    id: 'fb2-to-pdf',
    slug: 'fb2-to-pdf',
    icon: 'book-text',
    category: 'convert-to-pdf',
    acceptedFormats: ['.fb2', '.fb2.zip'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 20,
    features: ['preserve-formatting', 'preserve-images', 'chapter-structure', 'multiple-files'],
    relatedTools: ['epub-to-pdf', 'mobi-to-pdf', 'txt-to-pdf'],
  },

  // ==================== CONVERT FROM PDF ====================

  {
    id: 'pdf-to-jpg',
    slug: 'pdf-to-jpg',
    icon: 'file-image',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'jpg',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['all-pages', 'selected-pages', 'quality-setting', 'dpi-setting'],
    relatedTools: ['pdf-to-png', 'jpg-to-pdf', 'pdf-to-webp'],
  },
  {
    id: 'pdf-to-png',
    slug: 'pdf-to-png',
    icon: 'file-image',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'png',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['all-pages', 'selected-pages', 'transparency', 'dpi-setting'],
    relatedTools: ['pdf-to-jpg', 'png-to-pdf', 'pdf-to-webp'],
  },
  {
    id: 'pdf-to-webp',
    slug: 'pdf-to-webp',
    icon: 'file-image',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'webp',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['all-pages', 'selected-pages', 'quality-setting', 'compression'],
    relatedTools: ['pdf-to-jpg', 'pdf-to-png', 'webp-to-pdf'],
  },
  {
    id: 'pdf-to-bmp',
    slug: 'pdf-to-bmp',
    icon: 'file-image',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'bmp',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['all-pages', 'selected-pages', 'dpi-setting'],
    relatedTools: ['pdf-to-jpg', 'pdf-to-png', 'bmp-to-pdf'],
  },
  {
    id: 'pdf-to-tiff',
    slug: 'pdf-to-tiff',
    icon: 'file-image',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'tiff',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['all-pages', 'multi-page-tiff', 'dpi-setting', 'compression'],
    relatedTools: ['pdf-to-jpg', 'tiff-to-pdf', 'pdf-to-png'],
  },
  {
    id: 'pdf-to-svg',
    slug: 'pdf-to-svg',
    icon: 'file-code',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'svg',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['vector-output', 'scalable-quality', 'page-preview', 'individual-export'],
    relatedTools: ['pdf-to-png', 'svg-to-pdf', 'pdf-to-jpg'],
  },
  {
    id: 'pdf-to-greyscale',
    slug: 'pdf-to-greyscale',
    icon: 'palette',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['convert-colors', 'preserve-text', 'all-pages'],
    relatedTools: ['invert-colors', 'compress-pdf', 'background-color'],
  },
  {
    id: 'pdf-to-json',
    slug: 'pdf-to-json',
    icon: 'file-code',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'json',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['extract-text', 'extract-metadata', 'structured-output'],
    relatedTools: ['json-to-pdf', 'view-metadata', 'ocr-pdf'],
  },
  {
    id: 'pdf-to-docx',
    slug: 'pdf-to-docx',
    icon: 'file-text',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'docx',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['preserve-layout', 'editable-word', 'extract-images'],
    relatedTools: ['pdf-to-json', 'ocr-pdf', 'edit-pdf'],
  },
  {
    id: 'pdf-to-pptx',
    slug: 'pdf-to-pptx',
    icon: 'presentation',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pptx',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['preserve-layout', 'editable-slides', 'high-quality-images'],
    relatedTools: ['pdf-to-docx', 'pdf-to-excel', 'pdf-to-jpg'],
  },
  {
    id: 'pdf-to-excel',
    slug: 'pdf-to-excel',
    icon: 'table',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'xlsx',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['extract-tables', 'multiple-sheets', 'preserve-data'],
    relatedTools: ['pdf-to-json', 'pdf-to-docx', 'ocr-pdf'],
  },
  {
    id: 'pdf-to-markdown',
    slug: 'pdf-to-markdown',
    icon: 'file-code-2',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'md',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['extract-text', 'preserve-headings', 'detect-lists', 'page-range'],
    relatedTools: ['pdf-to-json', 'pdf-to-docx', 'ocr-pdf'],
  },


  // ==================== ORGANIZE & MANAGE ====================
  {
    id: 'ocr-pdf',
    slug: 'ocr-pdf',
    icon: 'scan-text',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['text-recognition', 'searchable-pdf', 'multiple-languages'],
    relatedTools: ['edit-pdf', 'pdf-to-json', 'compress-pdf'],
  },
  {
    id: 'alternate-merge',
    slug: 'alternate-merge',
    icon: 'shuffle',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: LARGE_FILE_SIZE,
    maxFiles: 10,
    features: ['alternate-pages', 'preserve-bookmarks', 'custom-order'],
    relatedTools: ['merge-pdf', 'organize-pdf', 'split-pdf'],
  },
  {
    id: 'add-attachments',
    slug: 'add-attachments',
    icon: 'paperclip',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['embed-files', 'multiple-attachments', 'any-format'],
    relatedTools: ['extract-attachments', 'edit-attachments', 'edit-metadata'],
  },
  {
    id: 'extract-attachments',
    slug: 'extract-attachments',
    icon: 'download',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'zip',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['extract-all', 'zip-output', 'batch-extract'],
    relatedTools: ['add-attachments', 'edit-attachments', 'pdf-to-zip'],
  },
  {
    id: 'extract-images',
    slug: 'extract-images',
    icon: 'image-down',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'zip',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 20,
    features: ['extract-all-images', 'filter-small', 'download-zip', 'batch-extract'],
    relatedTools: ['pdf-to-jpg', 'pdf-to-png', 'extract-attachments'],
  },
  {
    id: 'edit-attachments',
    slug: 'edit-attachments',
    icon: 'file-edit',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['view-attachments', 'remove-attachments', 'rename-attachments'],
    relatedTools: ['add-attachments', 'extract-attachments', 'edit-metadata'],
  },
  {
    id: 'divide-pages',
    slug: 'divide-pages',
    icon: 'table-columns-split',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['horizontal-split', 'vertical-split', 'custom-divisions'],
    relatedTools: ['split-pdf', 'n-up-pdf', 'posterize-pdf'],
  },
  {
    id: 'add-blank-page',
    slug: 'add-blank-page',
    icon: 'file-plus-2',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['insert-position', 'page-size', 'multiple-pages'],
    relatedTools: ['organize-pdf', 'delete-pages', 'merge-pdf'],
  },
  {
    id: 'reverse-pages',
    slug: 'reverse-pages',
    icon: 'arrow-down-z-a',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['reverse-order', 'batch-process'],
    relatedTools: ['organize-pdf', 'rotate-pdf', 'split-pdf'],
  },
  {
    id: 'rotate-custom',
    slug: 'rotate-custom',
    icon: 'refresh-ccw',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['custom-angle', 'selected-pages', 'preview'],
    relatedTools: ['rotate-pdf', 'organize-pdf', 'fix-page-size'],
  },
  {
    id: 'rotate-pdf',
    slug: 'rotate-pdf',
    icon: 'rotate-cw',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['90-degree', '180-degree', '270-degree', 'selected-pages'],
    relatedTools: ['organize-pdf', 'crop-pdf', 'fix-page-size'],
  },
  {
    id: 'n-up-pdf',
    slug: 'n-up-pdf',
    icon: 'layout-grid',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['2-up', '4-up', '6-up', '9-up', 'custom-layout'],
    relatedTools: ['divide-pages', 'posterize-pdf', 'combine-single-page', 'grid-combine'],
  },
  {
    id: 'grid-combine',
    slug: 'grid-combine',
    icon: 'layout-dashboard',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 100,
    features: ['combine-multiple-files', 'grid-layout', 'custom-spacing'],
    relatedTools: ['n-up-pdf', 'merge-pdf', 'combine-single-page'],
  },
  {
    id: 'combine-single-page',
    slug: 'combine-single-page',
    icon: 'unfold-vertical',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['continuous-scroll', 'stitch-pages', 'custom-spacing'],
    relatedTools: ['n-up-pdf', 'merge-pdf', 'posterize-pdf'],
  },
  {
    id: 'view-metadata',
    slug: 'view-metadata',
    icon: 'info',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'json',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['view-properties', 'view-author', 'view-dates', 'view-keywords'],
    relatedTools: ['edit-metadata', 'remove-metadata', 'pdf-to-json'],
  },
  {
    id: 'edit-metadata',
    slug: 'edit-metadata',
    icon: 'file-cog',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['edit-title', 'edit-author', 'edit-subject', 'edit-keywords'],
    relatedTools: ['view-metadata', 'remove-metadata', 'bookmark'],
  },
  {
    id: 'pdf-to-zip',
    slug: 'pdf-to-zip',
    icon: 'stretch-horizontal',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'zip',
    maxFileSize: LARGE_FILE_SIZE,
    maxFiles: 100,
    features: ['package-pdfs', 'compression', 'batch-process'],
    relatedTools: ['merge-pdf', 'extract-attachments', 'split-pdf'],
  },
  {
    id: 'compare-pdfs',
    slug: 'compare-pdfs',
    icon: 'git-compare',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 2,
    features: ['side-by-side', 'highlight-differences', 'overlay-mode'],
    relatedTools: ['merge-pdf', 'view-metadata', 'edit-pdf'],
  },
  {
    id: 'posterize-pdf',
    slug: 'posterize-pdf',
    icon: 'notepad-text-dashed',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['split-large-page', 'custom-grid', 'overlap-setting'],
    relatedTools: ['n-up-pdf', 'divide-pages', 'fix-page-size'],
  },


  // ==================== OPTIMIZE & REPAIR ====================
  {
    id: 'fix-page-size',
    slug: 'fix-page-size',
    icon: 'ruler-dimension-line',
    category: 'optimize-repair',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['standardize-size', 'custom-size', 'preserve-content'],
    relatedTools: ['page-dimensions', 'crop-pdf', 'rotate-pdf'],
  },
  {
    id: 'linearize-pdf',
    slug: 'linearize-pdf',
    icon: 'gauge',
    category: 'optimize-repair',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: LARGE_FILE_SIZE,
    maxFiles: 10,
    features: ['fast-web-view', 'optimize-streaming', 'batch-process'],
    relatedTools: ['compress-pdf', 'repair-pdf', 'sanitize-pdf'],
  },
  {
    id: 'page-dimensions',
    slug: 'page-dimensions',
    icon: 'ruler',
    category: 'optimize-repair',
    acceptedFormats: ['.pdf'],
    outputFormat: 'json',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['analyze-size', 'orientation', 'units-conversion'],
    relatedTools: ['fix-page-size', 'crop-pdf', 'view-metadata'],
  },
  {
    id: 'remove-restrictions',
    slug: 'remove-restrictions',
    icon: 'unlink',
    category: 'optimize-repair',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['remove-password', 'remove-security', 'unlock-pdf'],
    relatedTools: ['decrypt-pdf', 'change-permissions', 'repair-pdf'],
  },
  {
    id: 'repair-pdf',
    slug: 'repair-pdf',
    icon: 'wrench',
    category: 'optimize-repair',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: LARGE_FILE_SIZE,
    maxFiles: 10,
    features: ['fix-corruption', 'recover-data', 'rebuild-structure'],
    relatedTools: ['compress-pdf', 'linearize-pdf', 'sanitize-pdf'],
  },

  // ==================== SECURE PDF ====================
  {
    id: 'encrypt-pdf',
    slug: 'encrypt-pdf',
    icon: 'lock',
    category: 'secure-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['password-protection', 'aes-encryption', 'permissions'],
    relatedTools: ['decrypt-pdf', 'change-permissions', 'sanitize-pdf'],
  },
  {
    id: 'sanitize-pdf',
    slug: 'sanitize-pdf',
    icon: 'brush-cleaning',
    category: 'secure-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['remove-metadata', 'remove-annotations', 'remove-scripts', 'remove-attachments'],
    relatedTools: ['remove-metadata', 'flatten-pdf', 'find-and-redact'],
  },
  {
    id: 'find-and-redact',
    slug: 'find-and-redact',
    icon: 'search-x',
    category: 'secure-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['search-text', 'batch-redact', 'regex-search', 'selective-redact', 'preview-matches'],
    relatedTools: ['sanitize-pdf', 'edit-pdf', 'remove-metadata'],
  },
  {
    id: 'decrypt-pdf',
    slug: 'decrypt-pdf',
    icon: 'unlock',
    category: 'secure-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['remove-password', 'unlock-pdf', 'preserve-content'],
    relatedTools: ['encrypt-pdf', 'remove-restrictions', 'change-permissions'],
  },
  {
    id: 'flatten-pdf',
    slug: 'flatten-pdf',
    icon: 'layers',
    category: 'secure-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['flatten-forms', 'flatten-annotations', 'non-editable'],
    relatedTools: ['sanitize-pdf', 'remove-annotations', 'form-filler'],
  },
  {
    id: 'remove-metadata',
    slug: 'remove-metadata',
    icon: 'file-x',
    category: 'secure-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['strip-metadata', 'remove-author', 'remove-dates', 'privacy'],
    relatedTools: ['sanitize-pdf', 'edit-metadata', 'view-metadata'],
  },
  {
    id: 'change-permissions',
    slug: 'change-permissions',
    icon: 'shield-check',
    category: 'secure-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['print-permission', 'copy-permission', 'edit-permission', 'annotation-permission'],
    relatedTools: ['encrypt-pdf', 'decrypt-pdf', 'remove-restrictions'],
  },
  {
    id: 'digital-sign-pdf',
    slug: 'digital-sign-pdf',
    icon: 'file-key',
    category: 'secure-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['x509-certificate', 'pfx-p12-pem', 'visible-signature', 'signature-reason', 'timestamp'],
    relatedTools: ['validate-signature', 'encrypt-pdf', 'sign-pdf'],
  },
  {
    id: 'validate-signature',
    slug: 'validate-signature',
    icon: 'shield-check',
    category: 'secure-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'json',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['verify-signatures', 'certificate-info', 'integrity-check', 'batch-validation'],
    relatedTools: ['digital-sign-pdf', 'view-metadata', 'decrypt-pdf'],
  },

  // ==================== NEW TOOLS ====================
  {
    id: 'deskew-pdf',
    slug: 'deskew-pdf',
    icon: 'scan-line',
    category: 'optimize-repair',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: LARGE_FILE_SIZE,
    maxFiles: 10,
    features: ['auto-straighten', 'scanned-documents', 'angle-detection', 'batch-processing'],
    relatedTools: ['compress-pdf', 'ocr', 'repair-pdf'],
  },
  {
    id: 'pdf-booklet',
    slug: 'pdf-booklet',
    icon: 'book-open',
    category: 'organize-manage',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['booklet-layout', 'saddle-stitch', 'grid-modes', 'paper-sizes', 'preview'],
    relatedTools: ['n-up', 'posterize-pdf', 'print-pdf'],
  },
  {
    id: 'rasterize-pdf',
    slug: 'rasterize-pdf',
    icon: 'grid-2x2',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'image',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['dpi-control', 'png-jpeg-webp-pdf', 'page-range', 'batch-export'],
    relatedTools: ['pdf-to-jpg', 'pdf-to-png', 'extract-images'],
  },
  {
    id: 'markdown-to-pdf',
    slug: 'markdown-to-pdf',
    icon: 'file-type',
    category: 'convert-to-pdf',
    acceptedFormats: ['.md', '.markdown', '.txt'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['commonmark', 'gfm', 'code-highlighting', 'themes', 'tables'],
    relatedTools: ['text-to-pdf', 'html-to-pdf', 'word-to-pdf'],
  },
  {
    id: 'email-to-pdf',
    slug: 'email-to-pdf',
    icon: 'mail',
    category: 'convert-to-pdf',
    acceptedFormats: ['.eml', '.msg'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['inline-images', 'attachments', 'cc-bcc', 'date-formatting'],
    relatedTools: ['html-to-pdf', 'word-to-pdf', 'attachments'],
  },
  {
    id: 'cbz-to-pdf',
    slug: 'cbz-to-pdf',
    icon: 'book-image',
    category: 'convert-to-pdf',
    acceptedFormats: ['.cbz', '.zip'],
    outputFormat: 'pdf',
    maxFileSize: LARGE_FILE_SIZE,
    maxFiles: 10,
    features: ['comic-archive', 'image-extraction', 'page-order', 'page-sizes'],
    relatedTools: ['jpg-to-pdf', 'image-to-pdf', 'epub-to-pdf'],
  },
  {
    id: 'pdf-to-pdfa',
    slug: 'pdf-to-pdfa',
    icon: 'archive',
    category: 'optimize-repair',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: LARGE_FILE_SIZE,
    maxFiles: 10,
    features: ['pdfa-1b', 'pdfa-2b', 'pdfa-3b', 'long-term-archival', 'font-embedding'],
    relatedTools: ['compress-pdf', 'linearize-pdf', 'repair-pdf'],
  },
  {
    id: 'font-to-outline',
    slug: 'font-to-outline',
    icon: 'type',
    category: 'optimize-repair',
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 10,
    features: ['convert-fonts', 'vector-paths', 'compatibility', 'preserve-appearance'],
    relatedTools: ['compress-pdf', 'flatten-pdf', 'pdf-to-pdfa'],
  },
  {
    id: 'extract-tables',
    slug: 'extract-tables',
    icon: 'table',
    category: 'convert-from-pdf',
    acceptedFormats: ['.pdf'],
    outputFormat: 'data',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['json-export', 'markdown-export', 'csv-export', 'table-detection'],
    relatedTools: ['pdf-to-excel', 'pdf-to-json', 'ocr'],
  },
  {
    id: 'ocg-manager',
    slug: 'ocg-manager',
    icon: 'layers',
    category: 'optimize-repair',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['view-layers', 'toggle-layers', 'add-layers', 'delete-layers', 'rename-layers'],
    relatedTools: ['flatten', 'compress-pdf'],
  },
  {
    id: 'pdf-reader',
    slug: 'pdf-reader',
    icon: 'book-open',
    category: 'edit-annotate',
    acceptedFormats: ['.pdf'],
    outputFormat: 'view',
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
    maxFiles: 1,
    features: ['page-navigation', 'zoom', 'rotate', 'fullscreen', 'print', 'download'],
    relatedTools: ['sign-pdf', 'annotate-pdf'],
  },
];

/**
 * Get all tools (excluding disabled tools)
 */
export function getAllTools(): Tool[] {
  return tools.filter(tool => !tool.disabled);
}

/**
 * Get all tools including disabled ones (for admin)
 */
export function getAllToolsIncludingDisabled(): Tool[] {
  return tools;
}

/**
 * Get tool by ID
 */
export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id && !tool.disabled);
}

/**
 * Get tool by slug
 */
export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug && !tool.disabled);
}

/**
 * Get tools by category (excluding disabled tools)
 */
export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((tool) => tool.category === category && !tool.disabled);
}

/**
 * Get all tool IDs
 */
export function getAllToolIds(): string[] {
  return tools.map((tool) => tool.id);
}

/**
 * Check if a tool ID exists
 */
export function toolExists(id: string): boolean {
  return tools.some((tool) => tool.id === id);
}

/**
 * Popular tool IDs - curated list of commonly used tools
 * These tools remain in their original categories
 */
export const POPULAR_TOOL_IDS = [
  'merge-pdf',
  'split-pdf',
  'compress-pdf',
  'edit-pdf',
  'jpg-to-pdf',
  'pdf-to-jpg',
  'sign-pdf',
  'encrypt-pdf',
];

/**
 * Get popular tools
 * Returns a curated list of commonly used tools
 */
export function getPopularTools(): Tool[] {
  return POPULAR_TOOL_IDS
    .map(id => getToolById(id))
    .filter((tool): tool is Tool => tool !== undefined);
}

